name: twobrowin-study_otus-msa-25_project

services:
  postgres:
    image: postgres:16.9-alpine3.22
    ports:
      - "5432:5432"
    configs:
      - source: postgres-init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    environment:
      TZ: Europe/Moscow
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres

configs:
  postgres-init.sql:
    content: |
      CREATE DATABASE dev;
      GRANT ALL PRIVILEGES ON DATABASE dev TO postgres;

volumes:
  postgres-data:
