apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-hw3
  namespace: 2025-msa-demoapp-hw3

spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoapp-hw3
  template:
    metadata:
      labels:
        app: demoapp-hw3

    spec:
      containers:
      - name: demoapp-hw3
        image: twobrowin/2025-msa-project:demoapp-hw2-0.2
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8000
          name: service

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          timeoutSeconds: 5
          initialDelaySeconds: 40
          periodSeconds: 20
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          timeoutSeconds: 5
          periodSeconds: 10

        resources:
          requests:
            memory: "20Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "250m"